apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "pensjon-pdfmerger"
  namespace: "teampensjon"
  labels:
    team: "teampensjon"
spec:
  image: "{{{ image }}}"
  port: 8080
  liveness:
    path: "/ping"
    initialDelay: 3
    timeout: 1
  readiness:
    path: "/ping"
    initialDelay: 3
    timeout: 1
  prometheus:
    enabled: true
    path: "/metrics"
  ingresses:
    - "https://pensjon-pdfmerger.dev.adeo.no"
    - "https://pensjon-pdfmerger.dev.intern.nav.no"
