name: Build, push, and deploy

on: [push]

env:
  docker_image: test_image

jobs:

  build:
    name: Build Docker image
    permissions:
      id-token: "write"
      packages: "write"
    runs-on: ubuntu-latest
    outputs:
      image: "${{ steps.set-outputs.outputs.IMAGE }}"
    steps:
      - uses: actions/checkout@v7.0.1

      - name: Build Docker Image
        run: |
          docker build --tag ${docker_image} .

      - name: Test Docker Image
        run: |
          PDFMERGER_IMAGE=${docker_image} docker compose up --exit-code-from test

      - name: Build and push
        if: ${{ github.actor != 'dependabot[bot]' }}
        id: build_push
        uses: nais/docker-build-push@v0
        with:
          team: teampensjon

      - name: Set outputs
        if: ${{ github.actor != 'dependabot[bot]' }}
        shell: bash
        id: set-outputs
        run: |
          echo "IMAGE=${{ steps.build_push.outputs.image }}" >> $GITHUB_OUTPUT

  deployToProd:
    if: ${{ github.actor != 'dependabot[bot]' && github.ref == 'refs/heads/main' }}
    name: Deploy to Prod
    permissions:
      id-token: "write"
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1
      - name: Deploy to prod
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: nais-prod.yml
          IMAGE: "${{ needs.build.outputs.image }}"

  deployToDev:
    if: ${{ github.actor != 'dependabot[bot]' && github.ref == 'refs/heads/main' }}
    name: Deploy to dev
    permissions:
      id-token: "write"
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1
      - name: Deploy to dev
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: nais-dev.yml
          IMAGE: "${{ needs.build.outputs.image }}"
